### ISSUE TITLE
ts, singer tap, serverless ... nice

### ISSUE THREAD

**Issue by tomdavidson** [sbcottonhackathon2019/csvtojason#1]
@Ziggy-Z give me a shout if you are interested in a somewhat similar but full scale project, part-time or full time.

**Comment by Ziggy-Z** [comment]
It would be a pleasure to work on another project with you and learn more
about real world programming. I can let you know about my availability ASAP
if I could get the times for both part time or full time. Thank you for
reaching out to me.

Sincerely,
Zegedam Zegeye

**Comment by donpedro** [comment]
@tomdavidson if you like that stack, check out our project at [gulpetl.com](https://gulpetl.com/)

**Comment by tomdavidson** [comment]
@donpedro gulpetl.com is quite interesting, thank you!
